### PR TITLE
fix: fix context timeout on assignmentForHit

### PR DESCRIPTION
**Pull request by hubertusputu1**
## Issues 

- Context timeout on assignmentForHit
Screen Shot 2020-12-02 at 05 11 19

## Description
I found out that var nextToken always be empty on the start of the loop, so when we assign value on end of the loop, it won't affect anything.

rec1

### CODE REVIEW

**Review by npaton — COMMENTED** [review]
This is a for loop on purpose, it's paginating until there are no more records.

**Review by npaton — APPROVED** [review]
But given the pagination is 100 records, and we need it to work for today, let's just do that and fix this later. But reality is I don't think this will fix things. Do not merge!

**Comment by hubertusputu1** [comment]
I found out that that var `nextToken` always be empty on the start of the loop, so when we assign value on end of the loop, it won't affect anything.

**Review by npaton — APPROVED** [review]
Wow! Nice catch. I don't know how that happened. I don't know how it ever worked. Probably never worked, that's the answer.

**Pull request merged**
